DELETE FROM ASSET WHERE LOCATION = '6203';

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1000001','UNK','Acme Luminary Asset', 'ACTIVE', FALSE, 'LGT08801');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1000002','UNK','Acme Luminary Asset', 'ACTIVE', FALSE, 'LGT08802');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1000003','UNK','Acme Luminary Asset', 'ACTIVE', FALSE, 'LGT08803');