


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N280-SN001', 'NTNP Sump', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N281-SN001', 'NTSP Sump', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));


INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-N280'),(SELECT ID FROM LOCATION WHERE KEY = '6203-N280-SN001'),10);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-N281'),(SELECT ID FROM LOCATION WHERE KEY = '6203-N281-SN001'),10);
