

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'JTF201210', 'TV', 'JTF', 'Jet Fan', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Jet fans'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL011'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),(SELECT ID FROM LOCATION WHERE KEY = 'MCC201475'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'MCC201475'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'JTF201220', 'TV', 'JTF', 'Jet Fan', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Jet fans'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL011'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),(SELECT ID FROM LOCATION WHERE KEY = 'MCC201475'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'MCC201475'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'SST201210', 'TV', 'SST', 'Soft Starter', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Soft Starters'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'SST201210'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'SST201210'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RTD201211', 'TV', 'RTD', 'Resistance Temperature Detector', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201211'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201211'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RTD201212', 'TV', 'RTD', 'Resistance Temperature Detector', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201212'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201212'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RTD201213', 'TV', 'RTD', 'Resistance Temperature Detector', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201213'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201213'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RTD201214', 'TV', 'RTD', 'Resistance Temperature Detector', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201214'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201214'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RTD201215', 'TV', 'RTD', 'Resistance Temperature Detector', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201215'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201215'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'VIB201211', 'TV', 'VIB', 'Vibration monitoring sensor', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Vibration monitoring sensors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'VIB201211'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'VIB201211'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'VIB201212', 'TV', 'VIB', 'Vibration monitoring sensor', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Vibration monitoring sensors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'VIB201212'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201210'),(SELECT ID FROM LOCATION WHERE KEY = 'VIB201212'));



INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'SST201220', 'TV', 'SST', 'Soft Starter', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Soft Starters'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'SST201220'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'SST201220'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RTD201221', 'TV', 'RTD', 'Resistance Temperature Detector', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201221'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201221'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RTD201222', 'TV', 'RTD', 'Resistance Temperature Detector', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201222'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201222'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RTD201223', 'TV', 'RTD', 'Resistance Temperature Detector', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201223'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201223'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RTD201224', 'TV', 'RTD', 'Resistance Temperature Detector', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201224'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201224'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RTD201225', 'TV', 'RTD', 'Resistance Temperature Detector', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201225'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'RTD201225'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'VIB201221', 'TV', 'VIB', 'Vibration monitoring sensor', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Vibration monitoring sensors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'VIB201221'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'VIB201221'));

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'VIB201222', 'TV', 'VIB', 'Vibration monitoring sensor', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Vibration monitoring sensors'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'VIB201222'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201220'),(SELECT ID FROM LOCATION WHERE KEY = 'VIB201222'));


