------------------------------------------------------------------------------
-- Insert Script for Northern Tunnels (6203-L006) - Cross Passages and Sub Links
--
-- This version has 2 links (Northbound and Southbound) for each Cross Passage
--
------------------------------------------------------------------------------

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL001', 'Northbound, Between STNP & Cross Passage S01, West Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL002', 'Southbound, Between STNP & Cross Passage S01, East Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN301', 'Cross Passage S01', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL011', 'Southbound, Between Cross Passage S01 & S02, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL012', 'Northbound, Between Cross Passage S01 & S02, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN302', 'Cross Passage S02', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL021', 'Southbound, Between Cross Passage S02 & S03, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL022', 'Northbound, Between Cross Passage S02 & S03, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN303', 'Cross Passage S03', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL031', 'Southbound, Between Cross Passage S03 & S04, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL032', 'Northbound, Between Cross Passage S03 & S04, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN304', 'Cross Passage S04', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL041', 'Southbound, Between Cross Passage S04 & S05, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL042', 'Northbound, Between Cross Passage S04 & S05, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN305', 'Cross Passage S05', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL051', 'Southbound, Between Cross Passage S05 & S06, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL052', 'Northbound, Between Cross Passage S05 & S06, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN306', 'Cross Passage S06', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL061', 'Southbound, Between Cross Passage S06 & S07, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL062', 'Northbound, Between Cross Passage S06 & S07, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN307', 'Cross Passage S07', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL071', 'Southbound, Between Cross Passage S07 & S08, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL072', 'Northbound, Between Cross Passage S07 & S08, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN308', 'Cross Passage S08', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL081', 'Southbound, Between Cross Passage S08 & S09, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL082', 'Northbound, Between Cross Passage S08 & S09, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN309', 'Cross Passage S09', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL091', 'Southbound, Between Cross Passage S09 & S10, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL092', 'Northbound, Between Cross Passage S09 & S10, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN310', 'Cross Passage S10', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL101', 'Southbound, Between Cross Passage S10 & S11, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL102', 'Northbound, Between Cross Passage S10 & S11, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN311', 'Cross Passage S11', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL111', 'Southbound, Between Cross Passage S11 & S12, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL112', 'Northbound, Between Cross Passage S11 & S12, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN312', 'Cross Passage S12', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL121', 'Southbound, Between Cross Passage S12 & S13, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL122', 'Northbound, Between Cross Passage S12 & S13, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN313', 'Cross Passage S13', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL131', 'Southbound, Between Cross Passage S13 & S14, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL132', 'Northbound, Between Cross Passage S13 & S14, West Carriageway', 'ACTIVE', 'SUBLINK');


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN314', 'Cross Passage S14', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL141', 'Southbound, Between Cross Passage S14 & S15, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL142', 'Northbound, Between Cross Passage S14 & S15, West Carriageway', 'ACTIVE', 'SUBLINK');


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN315', 'Cross Passage S15', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL151', 'Southbound, Between Cross Passage S15 & S16, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL152', 'Northbound, Between Cross Passage S15 & S16, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN316', 'Cross Passage S16', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL161', 'Southbound, Between Cross Passage S16 & S17, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL162', 'Northbound, Between Cross Passage S16 & S17, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN317', 'Cross Passage S17', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL171', 'Southbound, Between Cross Passage S17 & S18, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL172', 'Northbound, Between Cross Passage S17 & S18, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN318', 'Cross Passage S18', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL181', 'Southbound, Between Cross Passage S18 & S19, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL182', 'Northbound, Between Cross Passage S18 & S19, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN319', 'Cross Passage S19', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL191', 'Southbound, Between Cross Passage S19 & S20, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL192', 'Northbound, Between Cross Passage S19 & S20, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN320', 'Cross Passage S20', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL201', 'Southbound, Between Cross Passage S20 & S21, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL202', 'Northbound, Between Cross Passage S20 & S21, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN321', 'Cross Passage S22', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL211', 'Southbound, Between Cross Passage S21 & S22, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL212', 'Northbound, Between Cross Passage S21 & S22, West Carriageway', 'ACTIVE', 'SUBLINK');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SN322', 'Cross Passage S22', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL221', 'Southbound, Between Cross Passage S22 & S23, East Carriageway', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L006SL222', 'Northbound, Between Cross Passage S22 & S23, West Carriageway', 'ACTIVE', 'SUBLINK');



INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL001'),10);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL002'),11);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN301'),12);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL011'),21);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL012'),22);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN302'),23);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL021'),31);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL022'),32);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN303'),33);


INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL031'),41);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL032'),42);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN304'),43);


INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL041'),51);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL042'),52);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN305'),53);


INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL051'),61);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL052'),62);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN306'),63);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL061'),71);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL062'),72);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN307'),73);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL071'),81);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL072'),82);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN308'),83);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL081'),91);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL082'),92);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN309'),93);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL091'),101);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL092'),102);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN310'),103);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL101'),111);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL102'),112);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN311'),113);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL111'),121);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL112'),122);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN312'),123);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL121'),131);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL122'),132);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN313'),133);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL131'),141);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL132'),142);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN314'),143);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL141'),151);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL142'),152);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN315'),153);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL151'),161);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL152'),162);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN316'),163);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL161'),171);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL162'),172);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN317'),173);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL171'),181);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL172'),182);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN318'),183);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL181'),191);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL182'),192);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN319'),193);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL191'),201);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL192'),202);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN320'),210);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL201'),211);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL202'),212);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN321'),220);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL211'),221);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL212'),222);


INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SN322'),230);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL221'),231);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L006SL222'),232);
