

INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'MCC201475', 'MCC', 'Motor Control Centre', 'ACTIVE', TRUE);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN210'),(SELECT ID FROM LOCATION WHERE KEY = 'MCC201475'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),(SELECT ID FROM LOCATION WHERE KEY = 'EEDB201321'),(SELECT ID FROM LOCATION WHERE KEY = 'MCC201475'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),null,(SELECT ID FROM LOCATION WHERE KEY = 'MCC201475'));


