
-- Charles Sturt Council Area Start
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'CA297-SP001', 'Langman Reserve', 'ACTIVE','OUTDOOR', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Council outdoor spaces'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'CA297'), (SELECT ID FROM LOCATION WHERE KEY = 'CA297-SP001'),3);
-- Charles Sturt Council Area Endv