

INSERT INTO LOCATION (ID, KEY, DISCIPLINE,  TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'JTF201323', 'TV', 'JTF', 'Jet Fan', 'ACTIVE', TRUE, (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Jet fans'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SL2011'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201323'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),(SELECT ID FROM LOCATION WHERE KEY = 'MCC201475'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201323'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'COMMS'),(SELECT ID FROM LOCATION WHERE KEY = 'MCC201475'),(SELECT ID FROM LOCATION WHERE KEY = 'JTF201323'));