


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B001', 'Substation SS05 A', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substations'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B001'),1);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B002', 'Substation SS05 B', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substations'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B002'),2);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B003', 'Control Building', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Control buildings'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B003'),3);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B004', 'Mobile Carrier Building', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Mobile carrier buildings'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B004'),4);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B005', 'Water Treatment Facility', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Water treatment facilities'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B005'),5);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B006', 'Ventilation Building', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Ventilation buildings'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B006'),6);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B007', 'MOC Grounds', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Facility grounds'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B007'),7);

