INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'BUILDINGS', 'Buildings', 'ACTIVE', 'GROUP');

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'), (SELECT ID FROM LOCATION WHERE KEY = 'T2D'), (SELECT ID FROM LOCATION WHERE KEY = 'BUILDINGS'),3);
