

DELETE FROM LOCATION;
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'T2D', 'Torrens to Darlington', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345', 'North-South Expressway (T2D Section)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '9999', 'Manchester Street', 'ACTIVE');


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-N001', 'Change, North-South Expressway to T2D', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L001', 'North of Torrens River Bridge', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-N002', 'Torrens River Bridge', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L002', 'Torrens River Bridge to Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-N003','Northern Tunnels, Northern Portal (NTNP)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003','Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-N004','Northern Tunnels, Southern Portal (NTSP)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L004', 'Open Motorway', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-N005', 'Southern Tunnels, Northern Portal (STNP)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005', 'Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-N006', 'Southern Tunnels, Southern Portal (STSP)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L006', 'South of Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-N007', 'Change, T2D to Southern Expressway', 'ACTIVE');


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '9999-N001', 'Manchester Street Maintenance Facility (MSMF)', 'ACTIVE');


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L001SN001', 'Outdoor Spaces, East & West (Charles Sturt Council)', 'ACTIVE');
--INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
--VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L001SN002', 'Outdoor Spaces, West (Charles Sturt Council)', 'ACTIVE');


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L002SN001', 'Outdoor Spaces, East & West (West Torrens Council)', 'ACTIVE');
--INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
--VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L002SN002', 'Outdoor Spaces, West (West Torrens Council)', 'ACTIVE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SL001', 'East Carriageway, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SL002', 'West Carriageway, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN001', 'Cross Tunnel 01, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN002', 'Cross Tunnel 02, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN003', 'Cross Tunnel 03, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN004', 'Cross Tunnel 04, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN005', 'Cross Tunnel 05, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN006', 'Cross Tunnel 06, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN007', 'Cross Tunnel 07, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN008', 'Cross Tunnel 08, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN009', 'Cross Tunnel 09, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN010', 'Cross Tunnel 10, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN011', 'Cross Tunnel 11, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN012', 'Cross Tunnel 12, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN013', 'Cross Tunnel 13, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L003SN014', 'Cross Tunnel 14, Northern Tunnels', 'ACTIVE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SL001', 'East Carriageway, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SL002', 'West Carriageway, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN001', 'Cross Tunnel 01, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN002', 'Cross Tunnel 02, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN003', 'Cross Tunnel 03, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN004', 'Cross Tunnel 04, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN005', 'Cross Tunnel 05, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN006', 'Cross Tunnel 06, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN007', 'Cross Tunnel 07, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN008', 'Cross Tunnel 08, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN009', 'Cross Tunnel 09, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN010', 'Cross Tunnel 10, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN011', 'Cross Tunnel 11, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN012', 'Cross Tunnel 12, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN013', 'Cross Tunnel 13, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN014', 'Cross Tunnel 14, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN015', 'Cross Tunnel 15, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN016', 'Cross Tunnel 16, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN017', 'Cross Tunnel 17, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN018', 'Cross Tunnel 18, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN019', 'Cross Tunnel 19, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN020', 'Cross Tunnel 20, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN021', 'Cross Tunnel 21, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN022', 'Cross Tunnel 22, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN023', 'Cross Tunnel 23, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN024', 'Cross Tunnel 24, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN025', 'Cross Tunnel 25, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN026', 'Cross Tunnel 26, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN027', 'Cross Tunnel 27, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN028', 'Cross Tunnel 28, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN029', 'Cross Tunnel 29, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN030', 'Cross Tunnel 30, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN031', 'Cross Tunnel 31, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '12345-L005SN032', 'Cross Tunnel 32, Southern Tunnels', 'ACTIVE');

DELETE FROM LOCATION_SYSTEM_HIERARCHY;
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),null, (SELECT ID FROM LOCATION WHERE KEY = 'T2D'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'T2D'), (SELECT ID FROM LOCATION WHERE KEY = '12345'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'T2D'), (SELECT ID FROM LOCATION WHERE KEY = '9999'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-N001'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L001'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-N002'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L002'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-N003'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-N004'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L004'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-N005'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-N006'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L006'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345'),(SELECT ID FROM LOCATION WHERE KEY = '12345-N007'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '9999'),(SELECT ID FROM LOCATION WHERE KEY = '9999-N001'));


INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L001'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L001SN001'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L002'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L002SN001'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SL001'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SL002'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN001'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN002'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN003'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN004'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN005'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN006'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN007'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN008'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN009'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN010'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN011'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN012'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN013'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L003SN014'));


INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SL001'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SL002'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN001'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN002'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN003'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN004'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN005'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN006'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN007'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN008'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN009'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN010'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN011'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN012'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN013'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN014'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN015'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN016'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN017'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN018'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN019'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN020'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN021'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN022'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN023'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN024'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN025'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN026'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN027'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN028'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN029'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN030'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN031'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005'),(SELECT ID FROM LOCATION WHERE KEY = '12345-L005SN032'));

