
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SL201', 'East Carriageway, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SL202', 'West Carriageway, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN201', 'Cross Tunnel 01, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN202', 'Cross Tunnel 02, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN203', 'Cross Tunnel 03, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN204', 'Cross Tunnel 04, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN205', 'Cross Tunnel 05, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN206', 'Cross Tunnel 06, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN207', 'Cross Tunnel 07, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN208', 'Cross Tunnel 08, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN209', 'Cross Tunnel 09, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN210', 'Cross Tunnel 10, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN211', 'Cross Tunnel 11, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN212', 'Cross Tunnel 12, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN213', 'Cross Tunnel 13, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN214', 'Cross Tunnel 14, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN215', 'Cross Tunnel 15, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN216', 'Cross Tunnel 16, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN217', 'Cross Tunnel 17, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN218', 'Cross Tunnel 18, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN219', 'Cross Tunnel 19, Northern Tunnels', 'ACTIVE');


INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SL201'),10);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SL202'),20);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN201'),201);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN202'),202);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN203'),203);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN204'),204);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN205'),205);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN206'),206);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN207'),207);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN208'),208);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN209'),209);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN210'),210);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN211'),211);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN212'),212);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN213'),213);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN214'),214);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN215'),215);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN216'),216);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN217'),217);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN218'),218);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN219'),219);


