

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN301', 'Cross Passage 01, Southern Tunnels', 'ACTIVE', 'SUBNODE');

/*

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010SN214'),214);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010SN215'),215);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010SN216'),216);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010SN217'),217);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010SN218'),218);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L010SN219'),219);


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SL301', 'Southbound, East Carriageway, Southern Tunnels', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SL302', 'Northbound, West Carriageway, Southern Tunnels', 'ACTIVE', 'SUBLINK');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN301', 'Cross Passage 01, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN302', 'Cross Passage 02, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN303', 'Cross Passage 03, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN304', 'Cross Passage 04, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN305', 'Cross Passage 05, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN306', 'Cross Passage 06, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN307', 'Cross Passage 07, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN308', 'Cross Passage 08, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN309', 'Cross Passage 09, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN310', 'Cross Passage 10, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN311', 'Cross Passage 11, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN312', 'Cross Passage 12, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN313', 'Cross Passage 13, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN314', 'Cross Passage 14, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN315', 'Cross Passage 15, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN316', 'Cross Passage 16, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN317', 'Cross Passage 17, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN318', 'Cross Passage 18, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN319', 'Cross Passage 19, Southern Tunnels', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN320', 'Cross Passage 20, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN321', 'Cross Passage 21, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN322', 'Cross Passage 22, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN323', 'Cross Passage 23, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN324', 'Cross Passage 24, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN325', 'Cross Passage 25, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN326', 'Cross Passage 26, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN327', 'Cross Passage 27, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN328', 'Cross Passage 28, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN329', 'Cross Passage 29, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN330', 'Cross Passage 30, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN331', 'Cross Passage 31, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN332', 'Cross Passage 32, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN333', 'Cross Passage 33, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN334', 'Cross Passage 34, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN335', 'Cross Passage 35, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN336', 'Cross Passage 36, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN337', 'Cross Passage 37, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN338', 'Cross Passage 38, Southern Tunnels', 'ACTIVE', 'SUBNODE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN339', 'Cross Passage 39, Southern Tunnels', 'ACTIVE', 'SUBNODE');

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SL301'),10);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SL302'),20);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN301'),30);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN302'),50);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN303'),60);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN304'),70);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN305'),80);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN306'),90);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN307'),100);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN308'),110);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN309'),120);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN310'),130);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN311'),140);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN312'),150);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN313'),160);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN314'),170);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN315'),180);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN316'),190);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN317'),200);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN318'),210);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN319'),220);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN320'),230);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN321'),240);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN322'),250);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN323'),260);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN324'),270);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN325'),280);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN326'),290);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN327'),300);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN328'),310);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN329'),320);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN330'),330);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN331'),340);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN332'),350);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN333'),360);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN334'),370);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN335'),380);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN336'),390);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN337'),400);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN338'),410);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN339'),420);

*/
