


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B001-S001', 'HV Switchroom A', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substation hv switchrooms'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011-B001'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B001-S001'),1);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B001-S002', 'HV Transformer A', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substation transformers'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011-B001'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B001-S002'),2);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B001-S003', 'LV Switchroom A', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substation lv switchrooms'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011-B001'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B001-S003'),3);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B001-S004', 'LV Cable Basement A', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substation cable rooms'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011-B001'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B001-S004'),4);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B002-S001', 'HV Switchroom B', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substation hv switchrooms'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011-B002'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B002-S001'),1);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B002-S002', 'HV Transformer B', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substation transformers'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011-B002'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B002-S002'),2);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B002-S003', 'LV Switchroom B', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substation lv switchrooms'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011-B002'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B002-S003'),3);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B002-S004', 'LV Cable Basement B', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substation cable rooms'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011-B002'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B002-S004'),4);










INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B007-S001', 'Compound Fence', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Snakeskin fence'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011-B007'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B007-S001'),1);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B007-S002', 'Compound Grounds', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Snakeskin fence'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011-B007'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B007-S002'),2);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0011-B007-S003', 'Fire Booster Space', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Fireboosters'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0011-B007'), (SELECT ID FROM LOCATION WHERE KEY = 'F0011-B007-S003'),3);
