
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SL201', 'Southbound, East Carriageway, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SL202', 'Northbound, West Carriageway, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN201', 'Cross Tunnel 01, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN202', 'Cross Tunnel 02, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN203', 'Cross Tunnel 03, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN204', 'Cross Tunnel 04, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN205', 'Cross Tunnel 05, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN206', 'Cross Tunnel 06, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN207', 'Cross Tunnel 07, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN208', 'Cross Tunnel 08, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN209', 'Cross Tunnel 09, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN210', 'Cross Tunnel 10, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN211', 'Cross Tunnel 11, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN212', 'Cross Tunnel 12, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN213', 'Cross Tunnel 13, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN214', 'Cross Tunnel 14, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN215', 'Cross Tunnel 15, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN216', 'Cross Tunnel 16, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN217', 'Cross Tunnel 17, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN218', 'Cross Tunnel 18, Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003SN219', 'Cross Tunnel 19, Northern Tunnels', 'ACTIVE');


INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SL201'),10);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SL202'),20);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN201'),201);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN202'),202);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN203'),203);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN204'),204);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN205'),205);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN206'),206);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN207'),207);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN208'),208);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN209'),209);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN210'),210);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN211'),211);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN212'),212);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN213'),213);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN214'),214);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN215'),215);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN216'),216);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN217'),217);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN218'),218);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L003SN219'),219);


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SL301', 'Southbound, East Carriageway, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SL302', 'Northbound, West Carriageway, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN301', 'Cross Tunnel 01, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN302', 'Cross Tunnel 02, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN303', 'Cross Tunnel 03, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN304', 'Cross Tunnel 04, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN305', 'Cross Tunnel 05, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN306', 'Cross Tunnel 06, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN307', 'Cross Tunnel 07, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN308', 'Cross Tunnel 08, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN309', 'Cross Tunnel 09, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN310', 'Cross Tunnel 10, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN311', 'Cross Tunnel 11, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN312', 'Cross Tunnel 12, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN313', 'Cross Tunnel 13, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN314', 'Cross Tunnel 14, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN315', 'Cross Tunnel 15, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN316', 'Cross Tunnel 16, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN317', 'Cross Tunnel 17, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN318', 'Cross Tunnel 18, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN319', 'Cross Tunnel 19, Southern Tunnels', 'ACTIVE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN320', 'Cross Tunnel 20, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN321', 'Cross Tunnel 21, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN322', 'Cross Tunnel 22, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN323', 'Cross Tunnel 23, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN324', 'Cross Tunnel 24, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN325', 'Cross Tunnel 25, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN326', 'Cross Tunnel 26, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN327', 'Cross Tunnel 27, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN328', 'Cross Tunnel 28, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN329', 'Cross Tunnel 29, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN330', 'Cross Tunnel 30, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN331', 'Cross Tunnel 31, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN332', 'Cross Tunnel 32, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN333', 'Cross Tunnel 33, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN334', 'Cross Tunnel 34, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN335', 'Cross Tunnel 35, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN336', 'Cross Tunnel 36, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN337', 'Cross Tunnel 37, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN338', 'Cross Tunnel 38, Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005SN339', 'Cross Tunnel 39, Southern Tunnels', 'ACTIVE');

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SL301'),10);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SL302'),20);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN301'),30);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN302'),50);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN303'),60);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN304'),70);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN305'),80);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN306'),90);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN307'),100);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN308'),110);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN309'),120);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN310'),130);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN311'),140);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN312'),150);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN313'),160);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN314'),170);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN315'),180);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN316'),190);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN317'),200);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN318'),210);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN319'),220);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN320'),230);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN321'),240);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN322'),250);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN323'),260);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN324'),270);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN325'),280);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN326'),290);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN327'),300);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN328'),310);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN329'),320);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN330'),330);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN331'),340);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN332'),350);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN333'),360);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN334'),370);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN335'),380);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN336'),390);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN337'),400);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN338'),410);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L005SN339'),420);


