

DELETE FROM LOCATION;
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '04500', 'South Eastern Freeway', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '04500-NODE-001', '04500 Node 01', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '04500-NODE-002', '04500 Node 02', 'ACTIVE');

DELETE FROM LOCATION_SYSTEM_HIERARCHY;
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),null, (SELECT ID FROM LOCATION WHERE KEY = '04500'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '04500'),(SELECT ID FROM LOCATION WHERE KEY = '04500-NODE-001'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '04500'),(SELECT ID FROM LOCATION WHERE KEY = '04500-NODE-002'));
