DELETE FROM LOCATION_SYSTEM_HIERARCHY;
DELETE FROM LOCATION;


-- T2D Level - Start
DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND PARENT_ID IN (SELECT ID FROM LOCATION WHERE KEY IN ('ROADS','COUNCILS'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND PARENT_ID = (SELECT ID FROM LOCATION WHERE KEY = 'T2D');

DELETE FROM LOCATION WHERE KEY IN ('T2D');
DELETE FROM LOCATION WHERE KEY IN ('Roads','Councils');
DELETE FROM LOCATION WHERE KEY IN ('6203','6780','62043','06464','06215','06212','06206','06586');
DELETE FROM LOCATION WHERE KEY IN ('62045','62046','62047','62048','62049','62050','62051','62052','62053','62054','62055');

DELETE FROM LOCATION WHERE KEY LIKE ('NCRN%');
DELETE FROM LOCATION WHERE KEY IN ('CSC','WTC','COUC','COMC');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'T2D', 'Torrens to Darlington', 'ACTIVE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'ROADS', 'Roads', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'COUNCILS', 'Councils', 'ACTIVE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203', 'North-South Motorway', 'ACTIVE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62037', 'North-South Motorway (from Manton Street)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62038', 'North-South Motorway (Grange Road)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62045', 'North-South Motorway (from Sir Donald Bradman Drive)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62046', 'North-South Motorway (to Richmond Road)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62047', 'North-South Motorway (from James Congdon Drive)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62048', 'North-South Motorway (from James Congdon Drive)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62049', 'North-South Motorway (from Richmond Road)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62050', 'North-South Motorway (to Richmond Road)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62051', 'North-South Motorway (to Anzac Highway)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62052', 'North-South Motorway (from Anzac Highway)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62053', 'North-South Motorway (to Cross Road)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62054', 'North-South Motorway (from Anzac Highway)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62055', 'North-South Motorway (from Cross Road)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62056', 'North-South Motorway (to Anzac Highway)', 'ACTIVE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62043', 'South Road', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6780', 'Southern Expressway', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '06464', 'Daws Road', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '06215', 'Cross Road', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '06212', 'Anzac Highway', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '06206', 'James Congdon Drive', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '06586', 'Sir Donald Bradman Drive', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '06580', 'Henley Beach Road', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '05857', 'Adam Street', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '05851', 'Grange/Manton Street', 'ACTIVE');
--INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
--VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '05851', 'Grange Road', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '05648', 'Port Road', 'ACTIVE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'NCRN001', 'Manchester Street', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'NCRN002', 'Tonsley Boulevard', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'NCRN003', 'Celtic Avenue', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'NCRN004', 'Barwell Avenue', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'NCRN005', 'Everard Avenue', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'NCRN006', 'West Thebarton Road', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'NCRN007', 'Ashwin Parade', 'ACTIVE');

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'CSC', 'Charles Sturt Council', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'WTC', 'West Torrens Council', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'COUC', 'City of Unley Council', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'COMC', 'City of Marion Council', 'ACTIVE');

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'), null, (SELECT ID FROM LOCATION WHERE KEY = 'T2D'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'), (SELECT ID FROM LOCATION WHERE KEY = 'T2D'), (SELECT ID FROM LOCATION WHERE KEY = 'ROADS'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'), (SELECT ID FROM LOCATION WHERE KEY = 'T2D'), (SELECT ID FROM LOCATION WHERE KEY = 'COUNCILS'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '6203'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62037'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62038'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62045'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62046'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62047'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62048'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62049'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62050'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62051'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62052'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62053'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62054'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62055'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62056'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '62043'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '6780'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '06464'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '06215'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '06212'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '06206'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '06586'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '06580'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '05857'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '05851'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = '05648'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = 'NCRN001'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = 'NCRN002'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = 'NCRN003'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = 'NCRN004'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = 'NCRN005'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = 'NCRN006'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'ROADS'), (SELECT ID FROM LOCATION WHERE KEY = 'NCRN007'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'COUNCILS'), (SELECT ID FROM LOCATION WHERE KEY = 'CSC'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'COUNCILS'), (SELECT ID FROM LOCATION WHERE KEY = 'WTC'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'COUNCILS'), (SELECT ID FROM LOCATION WHERE KEY = 'COUC'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'COUNCILS'), (SELECT ID FROM LOCATION WHERE KEY = 'COMC'));
-- T2D Level - End

-- 6203 Children Start
DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND PARENT_ID = (SELECT ID FROM LOCATION WHERE KEY = '6203');
DELETE FROM LOCATION WHERE KEY IN ('6203-L801','6203-L802','6203-L102','6203-N012','6203-N011','6203-L005','6203-N002',
                                   '6203-N009','6203-N008','6203-N007','6203-L004','6203-N056','6203-N005','6203-L003',
                                   '6203-N004', '6203-N003','6203-L002','6203-N092','6203-N022'
    );

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L801', 'Northbound on-ramp from Tonsley Boulevard', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L802', 'Southbound off-ramp to Tonsley Boulevard', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L102', 'Link south of Southern Tunnels, Southern Portal (STSP)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N012', 'STSP Maintenance and Operational Centre (MOC) Compound', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N011', 'Southern Tunnels, Southern Portal (STSP)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L005', 'Southern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N007', 'Southern Tunnels, Northern Portal (STNP)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N002','STSP, Mid Tunnel Power & Shaft Compound', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N009','STNP Communications Compound', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N008','STNP Maintenance and Operational Centre (MOC) Compound', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L004', 'Lowered Motorway', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N056','NTSP Maintenance and Operational Centre (MOC) Compound', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N005','Northern Tunnels, Southern Portal (NTSP)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L003','Northern Tunnels', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N004','Northern Tunnels, Northern Portal (NTNP)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N003','NTNP Maintenance and Operational Centre (MOC) Compound', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002', 'Link Taylors Bridge to Northern Tunnels, Northern Portal (NTNP)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N092', 'Taylors Bridge (River Torrens / Karrawirra Parri)', 'ACTIVE');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L022', 'Link north of Taylors Bridge', 'ACTIVE');

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-L801'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-L802'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-L102'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-N012'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-N011'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-L005'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-N007'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-N002'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-N009'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-N008'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-L004'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-N056'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-N005'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-L003'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-N004'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-N003'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-L002'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-N092'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203'), (SELECT ID FROM LOCATION WHERE KEY = '6203-L022'));
-- 6203 Children End

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62037-L001');
DELETE FROM LOCATION WHERE KEY IN ('62037-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62037-L001', 'Southbound on-ramp from Manton Street', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62037'), (SELECT ID FROM LOCATION WHERE KEY = '62037-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62038-L001');
DELETE FROM LOCATION WHERE KEY IN ('62038-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62038-L001', 'Northbound off-ramp to Grange Road', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62038'), (SELECT ID FROM LOCATION WHERE KEY = '62038-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62045-L001');
DELETE FROM LOCATION WHERE KEY IN ('62045-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62045-L001', 'Southbound on-ramp from Sir Donald Bradman Drive', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62045'), (SELECT ID FROM LOCATION WHERE KEY = '62045-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62046-L001');
DELETE FROM LOCATION WHERE KEY IN ('62046-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62046-L001', 'Southbound off-ramp to Richmond Road', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62046'), (SELECT ID FROM LOCATION WHERE KEY = '62046-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62047-L001');
DELETE FROM LOCATION WHERE KEY IN ('62047-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62047-L001', 'Southbound on-ramp from James Congdon Drive', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62047'), (SELECT ID FROM LOCATION WHERE KEY = '62047-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62048-L001');
DELETE FROM LOCATION WHERE KEY IN ('62048-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62048-L001', 'Northbound off-ramp from James Congdon Drive', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62048'), (SELECT ID FROM LOCATION WHERE KEY = '62048-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62049-L001');
DELETE FROM LOCATION WHERE KEY IN ('62049-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62049-L001', 'Northbound on-ramp from Richmond Road', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62049'), (SELECT ID FROM LOCATION WHERE KEY = '62049-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62050-L001');
DELETE FROM LOCATION WHERE KEY IN ('62050-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62050-L001', 'Northbound off-ramp to Richmond Road', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62050'), (SELECT ID FROM LOCATION WHERE KEY = '62050-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62051-L001');
DELETE FROM LOCATION WHERE KEY IN ('62051-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62051-L001', 'Southbound off-ramp to Anzac Highway', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62051'), (SELECT ID FROM LOCATION WHERE KEY = '62051-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62052-L001');
DELETE FROM LOCATION WHERE KEY IN ('62052-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62052-L001', 'Northbound on-ramp from Anzac Highway', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62052'), (SELECT ID FROM LOCATION WHERE KEY = '62052-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62053-L001');
DELETE FROM LOCATION WHERE KEY IN ('62053-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62053-L001', 'Southbound off-ramp to Cross Road', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62053'), (SELECT ID FROM LOCATION WHERE KEY = '62053-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62054-L001');
DELETE FROM LOCATION WHERE KEY IN ('62054-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62054-L001', 'Southbound on-ramp from Anzac Highway', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62054'), (SELECT ID FROM LOCATION WHERE KEY = '62054-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62055-L001');
DELETE FROM LOCATION WHERE KEY IN ('62055-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62055-L001', 'Northbound off-ramp from Cross Road', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62055'), (SELECT ID FROM LOCATION WHERE KEY = '62055-L001'));

DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = '62056-L001');
DELETE FROM LOCATION WHERE KEY IN ('62056-L001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '62056-L001', 'Northbound off-ramp to Anzac Highway', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '62056'), (SELECT ID FROM LOCATION WHERE KEY = '62056-L001'));

-- Manchester Maintenance Facility Building Start
DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = 'NCRN001-SN001');
DELETE FROM LOCATION WHERE KEY IN ('NCRN001-SN001');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'NCRN001-SN001', 'Manchester Street Maintenance Facility (MSMF)', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'NCRN001'), (SELECT ID FROM LOCATION WHERE KEY = 'NCRN001-SN001'));
-- Manchester Maintenance Facility Building End

-- Charles Sturt Council Area Start
DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = 'CSC-N022');
DELETE FROM LOCATION WHERE KEY IN ('CSC-N022');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'CSC-N022', 'Langman Reserve', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'CSC'), (SELECT ID FROM LOCATION WHERE KEY = 'CSC-N022'));
-- Charles Sturt Council Area End
