


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0391-B000', 'Substation SS05 A', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substations'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0391'), (SELECT ID FROM LOCATION WHERE KEY = 'F0391-B000'),1);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0391-B005', 'Substation SS05 B', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Substations'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0391'), (SELECT ID FROM LOCATION WHERE KEY = 'F0391-B005'),2);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0391-B004', 'Control Building', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Control buildings'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0391'), (SELECT ID FROM LOCATION WHERE KEY = 'F0391-B004'),3);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0391-B003', 'Computer Room', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Computer rooms'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0391'), (SELECT ID FROM LOCATION WHERE KEY = 'F0391-B003'),4);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0391-B002', 'Mobile Carrier Building', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Comms buildings'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0391'), (SELECT ID FROM LOCATION WHERE KEY = 'F0391-B002'),5);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0391-B006', 'Water Treatment Facility', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Water treatment facilties'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0391'), (SELECT ID FROM LOCATION WHERE KEY = 'F0391-B006'),6);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0391-B008', 'Ventilation Building', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Ventilation spaces'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0391'), (SELECT ID FROM LOCATION WHERE KEY = 'F0391-B008'),7);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0391-B009', 'MOC Grounds/Boundary', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Facility grounds'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0391'), (SELECT ID FROM LOCATION WHERE KEY = 'F0391-B009'),8);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'F0391-B007', 'Fire Booster Space', 'ACTIVE','FACILITY', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Fire boosters'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID,ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'F0391'), (SELECT ID FROM LOCATION WHERE KEY = 'F0391-B007'),9);