
-- Charles Sturt Council Area Start
DELETE FROM LOCATION_SYSTEM_HIERARCHY WHERE SYSTEM_ID = (SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT') AND LOCATION_ID = (SELECT ID FROM LOCATION WHERE KEY = 'CSC-N022');
DELETE FROM LOCATION WHERE KEY IN ('CSC-N022');
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'CSC-N022', 'Langman Reserve', 'ACTIVE','OUTDOOR');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'CSC'), (SELECT ID FROM LOCATION WHERE KEY = 'CSC-N022'));
-- Charles Sturt Council Area End
