------------------------------------------------------------------------------
-- Insert Script for Councils
--
------------------------------------------------------------------------------

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'CA297', 'Charles Sturt Council Area', 'ACTIVE', 'COUNCIL', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Council area'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'CA296', 'West Torrens Council Area', 'ACTIVE', 'COUNCIL', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Council area'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'CA395', 'City of Unley Council Area', 'ACTIVE', 'COUNCIL', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Council area'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'CA396', 'City of Marion Council Area', 'ACTIVE', 'COUNCIL', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Council area'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'CA397', 'City of Micham Council Area', 'ACTIVE', 'COUNCIL', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Council area'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'COUNCILS'), (SELECT ID FROM LOCATION WHERE KEY = 'CA297'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'COUNCILS'), (SELECT ID FROM LOCATION WHERE KEY = 'CA296'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'COUNCILS'), (SELECT ID FROM LOCATION WHERE KEY = 'CA395'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'COUNCILS'), (SELECT ID FROM LOCATION WHERE KEY = 'CA396'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'COUNCILS'), (SELECT ID FROM LOCATION WHERE KEY = 'CA397'));