

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RL08809', 'Road Lighting Pole', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RL08810', 'Road Lighting Pole', 'ACTIVE', TRUE);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LGT08801', 'Light', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LGT08802', 'Light', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LGT08803', 'Light', 'ACTIVE', TRUE);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L001'),(SELECT ID FROM LOCATION WHERE KEY = 'RL08809'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L001'),(SELECT ID FROM LOCATION WHERE KEY = 'RL08810'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'RL08809'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08801'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'RL08809'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08802'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'RL08810'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08803'));



INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LVMSB0881', 'Switchboard', 'ACTIVE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),null, (SELECT ID FROM LOCATION WHERE KEY = 'LVMSB0881'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),(SELECT ID FROM LOCATION WHERE KEY = 'LVMSB0881'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08801'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),(SELECT ID FROM LOCATION WHERE KEY = 'LVMSB0881'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08802'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),(SELECT ID FROM LOCATION WHERE KEY = 'LVMSB0881'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08803'));


