------------------------------------------------------------------------------
-- Insert Script for Northern Tunnels (6203-L002) - Cross Passages and Sub Links
--
-- This version has 2 links (Northbound and Southbound) for each Cross Passage
--
------------------------------------------------------------------------------

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL001', 'Between NTNP & Cross Passage N01, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL002', 'Between NTNP & Cross Passage N01, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL003', 'Invert Between NTNP & Cross Passage N01, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL004', 'Invert Between NTNP & Cross Passage N01, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SN010', 'Cross Passage N01', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL001'),11);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL002'),12);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL003'),13);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL004'),14);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN010'),15);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL011', 'Between Cross Passage N01 & N02, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL012', 'Between Cross Passage N01 & N02, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL013', 'Invert Between Cross Passage N01 & N02, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL014', 'Invert Between Cross Passage N01 & N02, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SN020', 'Cross Passage N02', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL011'),21);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL012'),22);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL013'),23);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL014'),24);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN020'),25);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL021', 'Between Cross Passage N02 & N03, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL022', 'Between Cross Passage N02 & N03, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL023', 'Invert Between Cross Passage N02 & N03, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL024', 'Invert Between Cross Passage N02 & N03, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SN030', 'Cross Passage N03', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL021'),31);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL022'),32);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL023'),33);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL024'),34);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN030'),35);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL031', 'Between Cross Passage N03 & N04, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL032', 'Between Cross Passage N03 & N04, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL033', 'Invert Between Cross Passage N03 & N04, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL034', 'Invert Between Cross Passage N03 & N04, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SN040', 'Cross Passage N04', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL031'),41);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL032'),42);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL033'),43);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL034'),44);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN040'),45);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL041', 'Between Cross Passage N04 & N05, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL042', 'Between Cross Passage N04 & N05, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL043', 'Invert Between Cross Passage N04 & N05, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL044', 'Invert Between Cross Passage N04 & N05, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SN050', 'Cross Passage N05', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL041'),51);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL042'),52);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL043'), 53);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL044'),54);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN050'),55);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL051', 'Between Cross Passage N05 & N06, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL052', 'Between Cross Passage N05 & N06, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL053', 'Invert Between Cross Passage N05 & N06, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL054', 'Invert Between Cross Passage N05 & N06, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SN060', 'Cross Passage N06', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL051'),61);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL052'),62);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL053'), 63);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL054'),64);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN060'),65);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL061', 'Between Cross Passage N06 & N07, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL062', 'Between Cross Passage N06 & N07, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL063', 'Invert Between Cross Passage N06 & N07, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL064', 'Invert Between Cross Passage N06 & N07, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SN070', 'Cross Passage N07', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL061'),71);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL062'),72);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL063'), 73);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL064'),74);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN070'),75);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL071', 'Between Cross Passage N07 & N08, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL072', 'Between Cross Passage N07 & N08, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL073', 'Invert Between Cross Passage N07 & N08, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL074', 'Invert Between Cross Passage N07 & N08, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SN080', 'Cross Passage N08', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL071'),81);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL072'),82);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL073'),83);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL074'),84);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN080'),85);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL081', 'Between Cross Passage N08 & N09, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL082', 'Between Cross Passage N08 & N09, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL083', 'Invert Between Cross Passage N08 & N09, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL084', 'Invert Between Cross Passage N08 & N09, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SN090', 'Cross Passage N09', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL081'),91);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL082'),92);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL083'),93);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL084'),94);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN090'),95);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL091', 'Between Cross Passage N09 & N10, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL092', 'Between Cross Passage N09 & N10, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL093', 'Invert Between Cross Passage N09 & N10, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL094', 'Invert Between Cross Passage N09 & N10, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SN100', 'Cross Passage N10', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL091'),101);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL092'),102);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL093'),103);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL094'),104);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN100'),105);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL101', 'Between Cross Passage N10 & N11, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL102', 'Between Cross Passage N10 & N11, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL103', 'Invert Between Cross Passage N10 & N11, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL104', 'Invert Between Cross Passage N10 & N11, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Invert sub-links'));
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SN110', 'Cross Passage N11', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL101'),111);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL102'),112);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL103'),113);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL104'),114);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN110'),115);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL821', 'Northern Tunnel Sump, West Carriageway, Northbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sump links'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL821'),5);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-L002-SL822', 'Northern Tunnel Sump, East Carriageway, Southbound', 'ACTIVE', 'SUBLINK', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel sump links'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SL822'),6);
