

INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RL08809', 'RL', 'Road Lighting Pole', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RL08810', 'RL', 'Road Lighting Pole', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RL01232', 'RL', 'Road Lighting Pole', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'RL07239', 'RL', 'Road Lighting Pole', 'ACTIVE', TRUE);

INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LGT08801', 'LGT', 'Light', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LGT08802', 'LGT', 'Light', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LGT08803', 'LGT', 'Light', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LGT03203', 'LGT', 'Light', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LGT02421', 'LGT', 'Light', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LGT09999', 'LGT', 'Light', 'ACTIVE', TRUE);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L001'),(SELECT ID FROM LOCATION WHERE KEY = 'RL08809'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L001'),(SELECT ID FROM LOCATION WHERE KEY = 'RL08810'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L001'),(SELECT ID FROM LOCATION WHERE KEY = 'RL01232'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L001'),(SELECT ID FROM LOCATION WHERE KEY = 'RL07239'));


INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'RL08809'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08801'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'RL08809'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08802'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'RL08810'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08803'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'RL01232'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT03203'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'RL01232'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT02421'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'RL07239'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT09999'));


INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LVMSB0881', 'LVMSB', 'Switchboard', 'ACTIVE', TRUE);
INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'LVMSB0732', 'LVMSB', 'Switchboard', 'ACTIVE', TRUE);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L001'),(SELECT ID FROM LOCATION WHERE KEY = 'LVMSB0881'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L001'),(SELECT ID FROM LOCATION WHERE KEY = 'LVMSB0732'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),null, (SELECT ID FROM LOCATION WHERE KEY = 'LVMSB0881'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),null, (SELECT ID FROM LOCATION WHERE KEY = 'LVMSB0732'));

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),(SELECT ID FROM LOCATION WHERE KEY = 'LVMSB0881'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08801'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),(SELECT ID FROM LOCATION WHERE KEY = 'LVMSB0881'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08802'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),(SELECT ID FROM LOCATION WHERE KEY = 'LVMSB0881'),(SELECT ID FROM LOCATION WHERE KEY = 'LGT08803'));


