


INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N003SN0001', 'NTNP Sump Node', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-N004SN0001', 'NTSP Sump Node', 'ACTIVE', 'SUBNODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Tunnel cross passages'));


INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-N003'),(SELECT ID FROM LOCATION WHERE KEY = '6203-N003SN0001'),10);

INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-N004'),(SELECT ID FROM LOCATION WHERE KEY = '6203-N004SN0001'),10);
