

INSERT INTO LOCATION (ID, KEY, TYPE, DESCRIPTION, STATUS, MAINTAINABLE_FLAG)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, 'EEDB201321', 'EEDB', 'Essential Electrical Distribution Board', 'ACTIVE', TRUE);
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = '6203-L002-SN010'),(SELECT ID FROM LOCATION WHERE KEY = 'EEDB201321'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'POWER'),null,(SELECT ID FROM LOCATION WHERE KEY = 'EEDB201321'));