
INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-C050','North South Motorway, NTNP Maintenance and Operational Centre (MOC) Compound', 'ACTIVE', 'NODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Maintenance and operational centre compounds'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'FACILITY'), (SELECT ID FROM LOCATION WHERE KEY = '6203-C050'), 40);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-C051','North South Motorway, NTSP Maintenance and Operational Centre (MOC) Compound', 'ACTIVE', 'NODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Maintenance and operational centre compounds'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'FACILITY'), (SELECT ID FROM LOCATION WHERE KEY = '6203-C051'), 70);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-C052','North South Motorway, STNP Maintenance and Operational Centre (MOC) Compound', 'ACTIVE', 'NODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Maintenance and operational centre compounds'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'FACILITY'), (SELECT ID FROM LOCATION WHERE KEY = '6203-C052'), 120);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-C057','North South Motorway, STNP Communications Compound', 'ACTIVE', 'NODE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'FACILITY'), (SELECT ID FROM LOCATION WHERE KEY = '6203-C057'), 130);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-C053','North South Motorway, STSP, Substation & Tunnel Vertical Shaft Compound', 'ACTIVE', 'NODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Maintenance and operational centre compounds'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'FACILITY'), (SELECT ID FROM LOCATION WHERE KEY = '6203-C053'), 150);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-C054','North South Motorway, STSP Maintenance and Operational Centre (MOC) Compound', 'ACTIVE', 'NODE', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Maintenance and operational centre compounds'));
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'FACILITY'), (SELECT ID FROM LOCATION WHERE KEY = '6203-C054'), 180);

INSERT INTO LOCATION (ID, KEY, DESCRIPTION, STATUS, TYPE)
VALUES (NEXT VALUE FOR LOCATION_ID_SEQ, '6203-C055', 'Manchester Street Maintenance Compound', 'ACTIVE','NODE');
INSERT INTO LOCATION_SYSTEM_HIERARCHY (ID, SYSTEM_ID, PARENT_ID, LOCATION_ID, ORDER)
VALUES (NEXT VALUE FOR LOCATION_SYSTEM_HIERARCHY_ID_SEQ,(SELECT ID FROM SYSTEM WHERE SYSTEM = 'DEFAULT'),(SELECT ID FROM LOCATION WHERE KEY = 'FACILITY'), (SELECT ID FROM LOCATION WHERE KEY = '6203-C055'), 220);
