
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A0394857','JTF','Jet Fan Asset', 'ACTIVE', FALSE, 'JTF201210', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Jet fans - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, PARENT, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A0394859','MTR','Electric Motor',  'A0394857', 'ACTIVE', FALSE, 'JTF201210', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Electric motors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, PARENT, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A5494359','VNA','Jet Fan Silencer',  'A0394857', 'ACTIVE', FALSE, 'JTF201210', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Ventilation hoods and extract points - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, PARENT, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A5494365','VNA','Jet Fan Silencer',  'A0394857', 'ACTIVE', FALSE, 'JTF201210', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Ventilation hoods and extract points - Asset'));


INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A4224257','UNK','Soft Starter Asset', 'ACTIVE', FALSE, 'SST201210', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Soft Starters - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A9324257','UNK','Resistance Temperature Detector Asset', 'ACTIVE', FALSE, 'RTD201211', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A5313257','UNK','Resistance Temperature Detector Asset', 'ACTIVE', FALSE, 'RTD201212', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A5513257','UNK','Resistance Temperature Detector Asset', 'ACTIVE', FALSE, 'RTD201213', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A544567', 'UNK','Resistance Temperature Detector Asset', 'ACTIVE', FALSE, 'RTD201214', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A523456', 'UNK','Resistance Temperature Detector Asset', 'ACTIVE', FALSE, 'RTD201215', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A834336', 'UNK','Vibration monitoring sensor', 'ACTIVE', FALSE, 'VIB201211', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Vibration monitoring sensors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A663445', 'UNK','Vibration monitoring sensor', 'ACTIVE', FALSE, 'VIB201212', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Vibration monitoring sensors - Asset'));



INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A4434857','JTF','Jet Fan Asset', 'ACTIVE', FALSE, 'JTF201220', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Jet fans - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A4293257','UNK','Soft Starter Asset', 'ACTIVE', FALSE, 'SST201220', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Soft Starters - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A4323257','UNK','Resistance Temperature Detector Asset', 'ACTIVE', FALSE, 'RTD201221', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A4313257','UNK','Resistance Temperature Detector Asset', 'ACTIVE', FALSE, 'RTD201222', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A6513257','UNK','Resistance Temperature Detector Asset', 'ACTIVE', FALSE, 'RTD201223', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A744567', 'UNK','Resistance Temperature Detector Asset', 'ACTIVE', FALSE, 'RTD201224', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A323456', 'UNK','Resistance Temperature Detector Asset', 'ACTIVE', FALSE, 'RTD201225', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Resistance Temperature Detectors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A334336', 'UNK','Vibration monitoring sensor', 'ACTIVE', FALSE, 'VIB201221', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Vibration monitoring sensors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A532545', 'UNK','Vibration monitoring sensor', 'ACTIVE', FALSE, 'VIB201222', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Vibration monitoring sensors - Asset'));
