
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-L','CARRIAGEWAY','North South Motorway - Northbound Carriageway - L', 'ACTIVE', TRUE, '6203', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Motorway Carriageways'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-R','CARRIAGEWAY','North South Motorway - Southbound Carriageway - R', 'ACTIVE', TRUE, '6203', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Motorway Carriageways'));


INSERT INTO ASSET (ID, KEY, PARENT, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-L1', '6203-L','LANE','North South Motorway - Lane - L1', 'ACTIVE', TRUE, '6203', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Motorway Lanes'));
INSERT INTO ASSET (ID, KEY, PARENT, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-L2', '6203-L','LANE','North South Motorway - Lane - L2', 'ACTIVE', TRUE, '6203', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Motorway Lanes'));
INSERT INTO ASSET (ID, KEY, PARENT, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-L3', '6203-L','LANE','North South Motorway - Lane - L3', 'ACTIVE', TRUE, '6203', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Motorway Lanes'));
INSERT INTO ASSET (ID, KEY, PARENT, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-LL1', '6203-L','LANE','North South Motorway - Lane - LL1', 'ACTIVE', TRUE, '6203', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Motorway Lanes'));
INSERT INTO ASSET (ID, KEY, PARENT, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-LL2', '6203-L','LANE','North South Motorway - Lane - LL2', 'ACTIVE', TRUE, '6203', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Motorway Lanes'));

INSERT INTO ASSET (ID, KEY, PARENT, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-R1', '6203-R','LANE','North South Motorway - Lane - R1', 'ACTIVE', TRUE, '6203', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Motorway Lanes'));
INSERT INTO ASSET (ID, KEY, PARENT, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-R2', '6203-R','LANE','North South Motorway - Lane - R2', 'ACTIVE', TRUE, '6203', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Motorway Lanes'));
INSERT INTO ASSET (ID, KEY, PARENT, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-R3', '6203-R','LANE','North South Motorway - Lane - R3', 'ACTIVE', TRUE, '6203', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Motorway Lanes'));
