
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1532231','UNK','Lighting Pole Footing', 'ACTIVE', FALSE, 'RL08809');
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1342001','UNK','Lighting Pole', 'ACTIVE', FALSE, 'RL08809');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1555231','UNK','Lighting Pole Footing', 'ACTIVE', FALSE, 'RL08810');
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1442002','UNK','Lighting Pole', 'ACTIVE', FALSE, 'RL08810');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1533231','UNK','Lighting Pole Footing', 'ACTIVE', FALSE, 'RL01232');
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1343401','UNK','Lighting Pole', 'ACTIVE', FALSE, 'RL01232');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1522531','UNK','Lighting Pole Footing', 'ACTIVE', FALSE, 'RL07239');
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1546401','UNK','Lighting Pole', 'ACTIVE', FALSE, 'RL07239');