
DELETE FROM ASSET WHERE LOCATION = '6203';

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-L','UNK','Linear Asset - Left Carriageway', 'ACTIVE', TRUE, '6203');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, PARENT)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-L1','UNK','Linear Asset - Lane L1', 'ACTIVE', TRUE, '6203', '6203-L');
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, PARENT)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-L2','UNK','Linear Asset - Lane L2', 'ACTIVE', TRUE, '6203', '6203-L');
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, PARENT)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-L3','UNK','Linear Asset - Lane L3', 'ACTIVE', TRUE, '6203', '6203-L');


INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-R','UNK','Linear Asset - Right Carriageway', 'ACTIVE', TRUE,'6203');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, PARENT)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-R1','UNK','Linear Asset - Lane R1', 'ACTIVE', TRUE, '6203', '6203-R');
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, PARENT)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-R2','UNK','Linear Asset - Lane R2', 'ACTIVE', TRUE, '6203', '6203-R');
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, PARENT)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-R3','UNK','Linear Asset - Lane R3', 'ACTIVE', TRUE, '6203', '6203-R');