--DELETE FROM ASSET WHERE LOCATION = '6203';

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1000001','UNK','Acme Luminary Asset', 'ACTIVE', FALSE, 'LGT08801');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1000002','UNK','Bunnings Luminary Asset', 'ACTIVE', FALSE, 'LGT08802');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1000003','UNK','Acme Luminary Asset', 'ACTIVE', FALSE, 'LGT08803');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1322435','UNK','Acme Luminary Asset', 'ACTIVE', FALSE, 'LGT03203');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1000004','UNK','Acme Luminary Asset', 'ACTIVE', FALSE, 'LGT02421');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A1000298','UNK','Acme Luminary Asset', 'ACTIVE', FALSE, 'LGT09999');