
DELETE FROM ASSET WHERE LOCATION = '6203';

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-L','UNK','6203 Linear Asset - Left Carriageway', 'ACTIVE', TRUE, '6203');

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'6203-R','UNK','6203 Linear Asset - Right Carriageway', 'ACTIVE', TRUE,'6203');