
INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A0394857','JTF','Jet Fan Asset', 'ACTIVE', FALSE, 'JTF201323', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Jet fans - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, PARENT, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A0394859','MTR','Electric Motor',  'A0394857', 'ACTIVE', FALSE, 'JTF201323', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Electric motors - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, PARENT, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A5494359','VNA','Jet Fan Silencer',  'A0394857', 'ACTIVE', FALSE, 'JTF201323', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Ventilation hoods and extract points - Asset'));

INSERT INTO ASSET (ID, KEY, TYPE, DESCRIPTION, PARENT, STATUS, LINEAR, LOCATION, CLASSIFICATION_ID)
VALUES (NEXT VALUE FOR ASSET_ID_SEQ,'A5494365','VNA','Jet Fan Silencer',  'A0394857', 'ACTIVE', FALSE, 'JTF201323', (SELECT ID FROM CLASSIFICATION WHERE DESCRIPTION = 'Ventilation hoods and extract points - Asset'));